export type LeiDoPoder = {
  number: number;
  title: string;
  keyPhrase: string;
  summary: string;
  applicationHint: string;
};

export const LEIS_DO_PODER: LeiDoPoder[] = [
  {
    number: 1,
    title: "Nunca ofusque o mestre",
    keyPhrase: "Faça os que estão acima de você sempre se sentirem superiores.",
    summary: "Ao mostrar seu talento em excesso, você desperta insegurança em quem tem poder sobre você. Deixe-os brilhar enquanto você cresce nos bastidores.",
    applicationHint: "Em reuniões com clientes ou gestores: apresente suas ideias como extensão das deles, não como suas. O crédito real vem com o tempo.",
  },
  {
    number: 2,
    title: "Nunca confie demais em amigos, aprenda a usar inimigos",
    keyPhrase: "Amigos se tornam inimigos com mais facilidade do que inimigos se tornam aliados.",
    summary: "Amigos esperam favores e ficam ressentidos quando não os recebem. Um ex-inimigo contratado tem muito mais a provar e raramente trai.",
    applicationHint: "Ao escolher parceiros ou fornecedores, prefira quem tem incentivo claro para entregar — não quem apenas quer agradar.",
  },
  {
    number: 3,
    title: "Esconda suas intenções",
    keyPhrase: "Mantenha as pessoas desequilibradas e no escuro sobre o que você está planejando.",
    summary: "Revelar seus planos antecipadamente dá ao oponente tempo para reagir e bloquear. A ambiguidade estratégica é uma vantagem.",
    applicationHint: "Antes de fechar um negócio importante, não sinalize urgência ou entusiasmo excessivo. Quem parece menos necessitado negocia melhor.",
  },
  {
    number: 4,
    title: "Fale sempre menos do que o necessário",
    keyPhrase: "Quando você está tentando impressionar, quanto mais você fala, mais comum parece.",
    summary: "Palavras em excesso entregam informação, revelam inseguranças e reduzem seu mistério. O silêncio é percebido como autoridade.",
    applicationHint: "Em negociações, após fazer sua proposta, fique em silêncio. Quem fala primeiro geralmente cede primeiro.",
  },
  {
    number: 5,
    title: "Muito depende da reputação — proteja-a com sua vida",
    keyPhrase: "A reputação é a pedra angular do poder.",
    summary: "Construída ao longo de anos, uma boa reputação pode ser destruída em dias. Ela precede você em qualquer ambiente e funciona mesmo quando você está ausente.",
    applicationHint: "Entregue sempre um pouco mais do que prometeu. Uma reputação de confiabilidade vale mais do que qualquer argumento de vendas.",
  },
  {
    number: 6,
    title: "Chame atenção a qualquer custo",
    keyPhrase: "Tudo é julgado pela aparência; o que é invisível não conta.",
    summary: "Em um mundo saturado de informação, ser ignorado é fatal. Presença e visibilidade são formas de poder mesmo antes de qualquer realização.",
    applicationHint: "Ao lançar um projeto ou serviço, invista em como ele será apresentado — a embalagem muitas vezes vale tanto quanto o conteúdo.",
  },
  {
    number: 7,
    title: "Faça os outros trabalharem por você, mas sempre leve o crédito",
    keyPhrase: "Use a sabedoria dos outros para avançar seus próprios fins.",
    summary: "Delegar e consolidar o trabalho alheio sob sua liderança não é desonestidade — é estratégia. Os melhores líderes curadoreiam e amplificam.",
    applicationHint: "Monte times complementares ao invés de tentar fazer tudo sozinho. Seu valor está na direção e síntese, não na execução.",
  },
  {
    number: 8,
    title: "Faça os outros virem até você — use isca se necessário",
    keyPhrase: "Quando você força o outro a agir, você está no controle.",
    summary: "Perseguir o oponente o esgota e o enfraquece. Quem atrai e espera tem vantagem posicional em qualquer negociação.",
    applicationHint: "Em vez de correr atrás de clientes, crie conteúdo ou casos de uso que os façam chegar até você prontos para comprar.",
  },
  {
    number: 9,
    title: "Ganhe pela ação, nunca pelo argumento",
    keyPhrase: "Qualquer vitória obtida pelo argumento é de curta duração.",
    summary: "Debates raramente mudam opiniões profundas — só criam resistência. Demonstrar e executar convence onde palavras falham.",
    applicationHint: "Ao enfrentar ceticismo de um cliente, ofereça um piloto ou prova de conceito em vez de mais argumentos. Resultados vencem debates.",
  },
  {
    number: 10,
    title: "Infecção: evite os infelizes e os azarados",
    keyPhrase: "O infortúnio de algumas pessoas é resultado de suas próprias ações.",
    summary: "Certas pessoas carregam padrões destrutivos que infectam quem está ao redor. Associação é poderosa — tanto para cima quanto para baixo.",
    applicationHint: "Avalie o histórico de projetos e relacionamentos das pessoas antes de fechar parcerias. Padrões se repetem.",
  },
  {
    number: 11,
    title: "Aprenda a manter as pessoas dependentes de você",
    keyPhrase: "Para manter sua independência, você deve ser sempre necessário.",
    summary: "Quem é facilmente substituível tem pouco poder. Tornar-se indispensável é a forma mais sustentável de segurança profissional.",
    applicationHint: "Identifique qual habilidade ou conhecimento seu é mais difícil de replicar e invista nela continuamente.",
  },
  {
    number: 12,
    title: "Use a honestidade seletiva e generosidade para desarmar sua vítima",
    keyPhrase: "Um gesto honesto cobre uma multidão de desonestidades.",
    summary: "Uma concessão genuína ou um ato de transparência estratégica cria confiança desproporcional. Use-os para abrir portas que argumentos fecham.",
    applicationHint: "Ao iniciar uma negociação difícil, comece admitindo uma limitação real sua. Isso desarma defensas e cria reciprocidade.",
  },
  {
    number: 13,
    title: "Ao pedir ajuda, apele ao interesse próprio das pessoas, nunca à misericórdia",
    keyPhrase: "Se você precisa de algo de uma pessoa, não a lembre do que fez por ela.",
    summary: "Apelar para a bondade é frágil. Mostrar como ajudar você serve ao interesse deles é muito mais poderoso e durável.",
    applicationHint: "Ao fazer um pedido, enquadre-o como uma oportunidade para o outro, não como um favor que você precisa.",
  },
  {
    number: 14,
    title: "Apresente-se como um amigo, trabalhe como um espião",
    keyPhrase: "Conhecimento sobre seus rivais é poder inestimável.",
    summary: "Informação é a base de toda estratégia. Quem mais escuta e menos revela tem vantagem consistente em qualquer ambiente.",
    applicationHint: "Em reuniões, faça mais perguntas do que declarações. Aprenda o que o cliente realmente quer antes de oferecer qualquer solução.",
  },
  {
    number: 15,
    title: "Esmague completamente o inimigo",
    keyPhrase: "Mais catástrofes foram geradas por meio inimigos do que por inimigos totais.",
    summary: "Deixar um oponente enfraquecido mas não eliminado cria rancor. Uma derrota completa é mais limpa e mais segura.",
    applicationHint: "Ao encerrar uma parceria ou contrato problemático, faça-o de forma definitiva e documentada. Relações pela metade criam mais problemas do que rompimentos claros.",
  },
  {
    number: 16,
    title: "Use a ausência para aumentar respeito e honra",
    keyPhrase: "Quanto mais você é visto e ouvido, mais comum você parece.",
    summary: "A raridade cria valor. Presença constante diminui seu mistério e percepção de valor. Ausências estratégicas criam desejo.",
    applicationHint: "Não responda toda mensagem imediatamente. Disponibilidade total sinaliza baixo valor — reserve tempo para parecer ocupado com coisas importantes.",
  },
  {
    number: 17,
    title: "Mantenha os outros em suspense: cultive um ar de imprevisibilidade",
    keyPhrase: "A previsibilidade dá controle às outras pessoas.",
    summary: "Quando os outros conseguem prever você, podem planejar contra você. A imprevisibilidade cria ansiedade que paralisa e mantém os outros na defensiva.",
    applicationHint: "Varie seu estilo de resposta, prazo e abordagem em negociações. Não deixe que seu padrão de comportamento se torne uma fórmula conhecida.",
  },
  {
    number: 18,
    title: "Não construa fortalezas para se proteger — o isolamento é perigoso",
    keyPhrase: "O mundo é perigoso e os inimigos estão em toda parte.",
    summary: "Fortalezas isolam e cortam o fluxo de informação vital. Misturar-se, circular e manter contatos é uma forma de proteção mais eficaz.",
    applicationHint: "Mantenha relacionamentos ativos mesmo fora de projetos. Redes de contato são a melhor proteção contra crises inesperadas.",
  },
  {
    number: 19,
    title: "Saiba com quem você está lidando — não ofenda a pessoa errada",
    keyPhrase: "Nunca assuma que a pessoa à sua frente é o que parece.",
    summary: "Subestimar ou ofender inadvertidamente o parceiro, cliente ou intermediário errado pode ter consequências desproporcionais. Leia as pessoas antes de agir.",
    applicationHint: "Antes de qualquer negociação importante, pesquise o histórico da pessoa. Quem ela é, o que valoriza, quais são seus pontos sensíveis.",
  },
  {
    number: 20,
    title: "Não se comprometa com ninguém",
    keyPhrase: "É o tolo que corre para cada lado que oferece suporte.",
    summary: "Manter neutralidade estratégica preserva suas opções. Quando você não está comprometido com nenhum lado, todos o cortejam.",
    applicationHint: "Em conflitos internos de equipe ou cliente, evite tomar partido antes de entender completamente o quadro. Neutralidade dá leverage.",
  },
  {
    number: 21,
    title: "Jogue um tolo para pegar um tolo — pareça mais simples do que seu alvo",
    keyPhrase: "Ninguém gosta de se sentir mais burro do que o próximo.",
    summary: "Revelar inteligência superior pode gerar ameaça. Às vezes, parecer menos capaz é a manobra mais inteligente.",
    applicationHint: "Ao apresentar uma ideia complexa, simplifique a linguagem e deixe o interlocutor chegar à conclusão sozinho — ele a defenderá como se fosse sua.",
  },
  {
    number: 22,
    title: "Use o efeito da rendição — transforme fraqueza em poder",
    keyPhrase: "Quando você é mais fraco, nunca lute por honra — renda-se.",
    summary: "A rendição estratégica não é derrota. É uma manobra que compra tempo, poupa recursos e frequentemente inverte a posição de poder.",
    applicationHint: "Quando um cliente ou parceiro tem razão, admita rápido e completamente. Resistência prolonga o conflito; rendição inteligente fecha a questão e constrói reputação.",
  },
  {
    number: 23,
    title: "Concentre suas forças",
    keyPhrase: "A conservação de energia é o segredo da força.",
    summary: "Dispersar esforços em múltiplas frentes enfraquece todos os ataques. Uma força concentrada supera várias forças dispersas.",
    applicationHint: "Identifique o projeto ou cliente que tem maior potencial agora e direcione a maioria dos seus recursos para lá. Profundidade bate amplitude.",
  },
  {
    number: 24,
    title: "Jogue o perfeito cortesão",
    keyPhrase: "O cortesão prospera em um mundo onde tudo gira em torno do poder.",
    summary: "Navegar estruturas de poder exige graça, tato e habilidade política. Observar as regras não escritas do ambiente é sobrevivência.",
    applicationHint: "Aprenda a cultura implícita de cada cliente ou parceiro antes de agir. O que funciona em um ambiente pode ser um erro em outro.",
  },
  {
    number: 25,
    title: "Re-crie a si mesmo",
    keyPhrase: "Não aceite os papéis que a sociedade lhe impõe.",
    summary: "Identidade não é destino. Quem se reinventa controla sua narrativa e mantém relevância ao longo do tempo.",
    applicationHint: "Revise seu posicionamento profissional ao menos uma vez por ano. O que te diferenciava há 3 anos pode ser commodity hoje.",
  },
  {
    number: 26,
    title: "Mantenha suas mãos limpas",
    keyPhrase: "Você deve parecer um modelo de civismo e eficiência.",
    summary: "Use intermediários para executar o trabalho sujo. Sua reputação de integridade é um ativo que vale proteger a qualquer custo.",
    applicationHint: "Ao precisar encerrar contratos ou dar feedbacks difíceis, estruture o processo para que pareça objetivo e baseado em critérios — não pessoal.",
  },
  {
    number: 27,
    title: "Jogue com a necessidade das pessoas de acreditar para criar um culto",
    keyPhrase: "As pessoas têm uma necessidade enorme de acreditar em algo.",
    summary: "Ofereça uma visão, um propósito, uma identidade coletiva e as pessoas se moverão para você. Liderança é tanto narrativa quanto execução.",
    applicationHint: "Ao construir uma equipe ou base de clientes, articule claramente o 'porquê' do seu trabalho. Propósito retém mais do que salário.",
  },
  {
    number: 28,
    title: "Entre na ação com ousadia",
    keyPhrase: "Qualquer empreendimento hesitante está condenado ao fracasso.",
    summary: "A timidez convida ao ataque. A ação decidida, mesmo imperfeita, projeta confiança e fecha janelas de resistência.",
    applicationHint: "Ao lançar algo novo, execute de forma visível e decisiva. Piloto eterno sem lançamento real é sinal de medo, não de cautela.",
  },
  {
    number: 29,
    title: "Planeje até o fim",
    keyPhrase: "O fim é tudo. Nunca perca de vista seus objetivos finais.",
    summary: "Vitórias táticas sem visão estratégica levam a derrotas. Planejar com antecedência evita ser surpreendido pelas consequências de ações de curto prazo.",
    applicationHint: "Antes de aceitar qualquer projeto, pergunte: onde isso me coloca em 12 meses? Esforço sem direção é energia desperdiçada.",
  },
  {
    number: 30,
    title: "Faça suas realizações parecerem sem esforço",
    keyPhrase: "Suas ações devem parecer naturais e executadas com facilidade.",
    summary: "Revelar quanto esforço algo custou diminui seu impacto e inspira imitação. A aparência de naturalidade amplifica o efeito de qualquer realização.",
    applicationHint: "Ao entregar um trabalho complexo, apresente o resultado de forma simples e confiante. O processo interno é seu — o cliente compra o resultado.",
  },
  {
    number: 31,
    title: "Controle as opções — faça os outros jogarem com as cartas que você distribuiu",
    keyPhrase: "A melhor ilusão de escolha: deixe o outro escolher entre o que você quer.",
    summary: "Dar às pessoas a aparência de escolha enquanto controla as opções é uma forma sofisticada de poder. A percepção de autonomia cria colaboração.",
    applicationHint: "Em propostas comerciais, ofereça 2-3 opções construídas em torno do que você quer entregar. O cliente escolhe, mas você estruturou o campo.",
  },
  {
    number: 32,
    title: "Jogue com as fantasias das pessoas",
    keyPhrase: "A verdade é frequentemente evitada porque é feia e perturbadora.",
    summary: "As pessoas preferem sonhos agradáveis à realidade dura. Quem alimenta a fantasia certa tem seguidores; quem destrói fantasias tem inimigos.",
    applicationHint: "Ao vender uma solução, venda o estado futuro que o cliente quer alcançar, não as especificações técnicas. Conecte ao desejo, não à razão.",
  },
  {
    number: 33,
    title: "Descubra o ponto fraco de cada homem",
    keyPhrase: "Todo mundo tem um ponto fraco, uma porta aberta à influência.",
    summary: "Entender o que motiva, preocupa ou seduz o outro é a base de qualquer influência real. Você não precisa atacar essa fraqueza — apenas conhecê-la.",
    applicationHint: "Em cada relacionamento comercial importante, identifique o que o outro mais valoriza e o que mais teme. Isso informa como você comunica e posiciona.",
  },
  {
    number: 34,
    title: "Seja real em suas maneiras — o grande senhor",
    keyPhrase: "A forma como você age determina como você é tratado.",
    summary: "Comportar-se com a postura e confiança de quem tem poder tende a atrair esse mesmo poder. Autoconfiança genuína é uma forma de magnetismo.",
    applicationHint: "Antes de uma reunião importante, revise mentalmente suas conquistas. Entre com a postura de quem já tem o que o outro precisa.",
  },
  {
    number: 35,
    title: "Domine a arte do timing",
    keyPhrase: "Nunca pareça com pressa — pressa trai falta de controle.",
    summary: "O momento certo multiplica qualquer ação. Agir antes ou depois do ponto ideal desperdiça recursos e cria resistência desnecessária.",
    applicationHint: "Não feche negociações importantes em prazos externos. Quem domina o timing controla a negociação. Espere pelo momento em que o outro precisa mais.",
  },
  {
    number: 36,
    title: "Despreze o que não pode ter — ignorar é a melhor vingança",
    keyPhrase: "Ao reconhecer algo indesejável, você o fortalece.",
    summary: "Reagir a irritações menores dá poder a elas. Ignorar com elegância é frequentemente mais poderoso do que qualquer resposta.",
    applicationHint: "Quando um cliente ou parceiro faz uma crítica de má-fé ou comparação com concorrente, não defenda. Siga em frente como se não fosse relevante.",
  },
  {
    number: 37,
    title: "Crie espetáculos marcantes",
    keyPhrase: "Imagens marcantes criam memória onde palavras falham.",
    summary: "Grandes eventos, apresentações memoráveis e gestos visuais ficam na memória muito mais do que argumentos racionais. O espetáculo cria impacto duradouro.",
    applicationHint: "Invista em como você apresenta resultados. Uma visualização bem feita de dados ou uma demonstração ao vivo vale dez slides de texto.",
  },
  {
    number: 38,
    title: "Pense como você quiser, mas comporte-se como os outros",
    keyPhrase: "Se você insulta valores sagrados, você fará inimigos.",
    summary: "Singularidade de pensamento é um ativo; exibição de singularidade é um risco. Conformidade exterior protege a liberdade interior.",
    applicationHint: "Em novos ambientes profissionais, observe e adapte seu estilo de comunicação antes de introduzir formas diferentes de pensar. Entre devagar, mude por dentro.",
  },
  {
    number: 39,
    title: "Agite a água para pescar",
    keyPhrase: "A raiva e a emoção são estrategicamente contraproducentes.",
    summary: "Manter a calma quando os outros perdem o controle é uma vantagem enorme. Quem provoca emoções nos outros enquanto permanece frio está no comando.",
    applicationHint: "Em negociações tensas, quanto mais o outro escala emocionalmente, mais você desacelera e fala com calma. O contraste te posiciona como o adulto na sala.",
  },
  {
    number: 40,
    title: "Despreze as coisas gratuitas",
    keyPhrase: "O que tem preço tem valor; o que é gratuito é perigoso.",
    summary: "Favores gratuitos criam obrigações ocultas. Pagar pelo que você recebe mantém sua independência e elimina dívidas emocionais.",
    applicationHint: "Seja cauteloso com serviços 'gratuitos' de parceiros ou plataformas. Entenda o modelo por trás — você sempre está pagando de alguma forma.",
  },
  {
    number: 41,
    title: "Evite seguir os passos de um grande homem",
    keyPhrase: "O que veio primeiro sempre parecerá melhor.",
    summary: "Suceder um predecessor famoso é uma armadilha — você sempre será comparado desfavoravelmente. Crie seu próprio território ao invés de disputar o legado de outro.",
    applicationHint: "Ao entrar em um mercado ou categoria estabelecida, redefina o jogo ao invés de competir nos mesmos critérios do líder. Mude o campo de batalha.",
  },
  {
    number: 42,
    title: "Golpeie o pastor e as ovelhas se dispersam",
    keyPhrase: "Os problemas frequentemente têm uma única fonte.",
    summary: "Em qualquer grupo com dinâmica problemática, existe geralmente uma pessoa-chave alimentando o conflito. Neutralize a fonte ao invés de tratar sintomas.",
    applicationHint: "Quando há resistência coletiva a um projeto, identifique quem está liderando essa resistência. Uma conversa direta com esse indivíduo frequentemente resolve o que nenhuma reunião de grupo resolve.",
  },
  {
    number: 43,
    title: "Trabalhe sobre o coração e a mente dos outros",
    keyPhrase: "A coerção cria reação; sedução cria colaboração.",
    summary: "Forçar obediência cria resistência passiva. Conquistar o engajamento genuíno, mesmo que leve mais tempo, produz resultados muito mais duradouros.",
    applicationHint: "Ao implementar mudanças de processo com uma equipe ou cliente, envolva-os na definição da solução. Pessoas defendem o que ajudaram a criar.",
  },
  {
    number: 44,
    title: "Desarme e irrite com o efeito espelho",
    keyPhrase: "O espelho tem muitos usos — o mais poderoso é refletir o outro.",
    summary: "Copiar as ações do adversário — usar os mesmos argumentos, os mesmos métodos — o força a ver seu próprio comportamento. É desconcertante e frequentemente paralisante.",
    applicationHint: "Quando um cliente usa táticas de pressão (prazos artificiais, ameaças de concorrente), espelhe com calma: 'Interessante, isso é exatamente o que o concorrente também diz.'",
  },
  {
    number: 45,
    title: "Pregue a necessidade de mudança, mas nunca reforme demais de uma vez",
    keyPhrase: "Muito inovação de uma vez assusta as pessoas.",
    summary: "Mudanças radicais imediatas geram rejeição mesmo quando são melhores. Introduzir novidades incrementalmente, ancoradas no familiar, acelera a adoção.",
    applicationHint: "Ao propor transformações digitais ou processuais, comece pelo menor passo possível que já mostre valor. Cada vitória pequena financia a próxima.",
  },
  {
    number: 46,
    title: "Nunca pareça muito perfeito",
    keyPhrase: "A inveja cria inimigos silenciosos.",
    summary: "Exibir perfeição em tudo provoca inveja e ressentimento. Mostrar falhas cuidadosamente selecionadas humaniza e desativa a hostilidade.",
    applicationHint: "Em apresentações e propostas, admita uma limitação real e pequena proativamente. Isso aumenta a credibilidade do restante e desarma ceticismo.",
  },
  {
    number: 47,
    title: "Não vá além do objetivo marcado: ao vencer, saiba quando parar",
    keyPhrase: "O sucesso faz você ir além do seu objetivo inicial.",
    summary: "A vitória pode criar a ilusão de invencibilidade. Saber parar no pico preserva o que foi conquistado e evita o excesso que destrói.",
    applicationHint: "Após fechar um bom negócio, não tente empilhar pedidos imediatamente. Deixe o relacionamento respirar antes de expandir. Ganância queima confiança.",
  },
  {
    number: 48,
    title: "Assuma a forma: a lei da fluidez",
    keyPhrase: "Rigidez é a morte — fluidez é sobrevivência.",
    summary: "A capacidade de adaptar forma, estratégia e posicionamento conforme o contexto muda é a lei final e mais abrangente. Identidade fixa é vulnerabilidade.",
    applicationHint: "Revise regularmente o que está funcionando e o que não está. Apego a abordagens que funcionaram no passado é o maior obstáculo ao crescimento futuro.",
  },
];

const REF_EPOCH = new Date("2024-01-01T00:00:00Z").getTime();

export function getLeiDoDia(now: Date): LeiDoPoder {
  const todayUtc = Date.UTC(now.getFullYear(), now.getMonth(), now.getDate());
  const dayOffset = Math.floor((todayUtc - REF_EPOCH) / 86400000);
  const index = ((dayOffset % LEIS_DO_PODER.length) + LEIS_DO_PODER.length) % LEIS_DO_PODER.length;
  return LEIS_DO_PODER[index];
}
