BEGIN;

ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS monthly_agreed_amount NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS monthly_agreed_hours NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS daily_agreed_hours NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS workdays TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS daily_rate NUMERIC(10,2);

COMMIT;
